common: &common
  bucket: uplo-dev
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
  bucket: uplo
