development:
  bucket: uplo
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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

staging:
  bucket: uplo-dev
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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
  
test:
  bucket: uplo
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 0rUsMMg8UdwVvCBbSwnOo72qnXE5hkHSqSPp
  
production:
  bucket: uplo
  access_key_id: AKIAIOYCWZFROQJEEBYQ
  secret_access_key: 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
