development: &development
  facebook:
    api_key: '1681267485345167'
    secret: 'baae7dac3520d70ba14edf6c1273c547'
  twitter:
    consumer_key: "CJoc3Hxu5ZvjU6UVXUpA"
    consumer_secret: "6POCeNga1Do6apmiArT1GrlNjRjHOikPTlMXxfIM"
  tumblr:
    consumer_key: "GJWrwpoDqLW3cVZtofYBuOlqMXDBZX5dB5ZLCBrQDfVX2CeDQh"
    consumer_secret: "ZzdTKenzNW70KP0Hew6SCuBMDEB7zhRmILi9ivaRTNBYRKTNZL"
  flickr:
    api_key: "e543b1d3d5f8247068f54191918bc78c"
    secret: "0b3fdd798b301fcd"

test:
  <<: *development

staging:
  <<: *development
