development: &development
  facebook:
    api_key: "618207694880677"
    secret: "b9e266fe550fcc22f8af4d12d458e49d"
    name: 'uplo'
  twitter:
    consumer_key: "CJoc3Hxu5ZvjU6UVXUpA"
    consumer_secret: "6POCeNga1Do6apmiArT1GrlNjRjHOikPTlMXxfIM"
  tumblr:
    consumer_key: "GJWrwpoDqLW3cVZtofYBuOlqMXDBZX5dB5ZLCBrQDfVX2CeDQh"
    consumer_secret: "ZzdTKenzNW70KP0Hew6SCuBMDEB7zhRmILi9ivaRTNBYRKTNZL"
  flickr:
    api_key: "e543b1d3d5f8247068f54191918bc78c"
    secret: "0b3fdd798b301fcd"

test:
  <<: *development

staging:
  <<: *development

production: 
  facebook:
    api_key: "164091983778781"
    secret: "39feaa2763d6cf829991ebeff78f1439"
    name: "uploapp"
  twitter: 
    consumer_key: '7jHkC1FBt3fvkpLD6Ul8g'
    consumer_secret: 'n9R54l0LzvZOAOMrs51VvEkxS9VUN5k5puJfCPD4pFw'
 